# Generated by Django 2.0.6 on 2019-05-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='soort',
            field=models.CharField(choices=[('X', 'Kies soort reptiel'), ('H', 'Hagedis'), ('S', 'Slang'), ('D', 'Schildpad'), ('K', 'Krokodil')], default='X', max_length=1),
        ),
    ]
